// src/components/Header/Header.svelte
<script>
  export let y;
  import links from "../../data/Links";
</script>

<header
  class={"sticky z-[10] top-0 duration-200 px-6 flex items-center justify-between border-b border-solid " +
    (y > 0
      ? " py-4 bg-slate-950 border-violet-950"
      : " py-6 bg-transparent border-transparent")}
>
  <h1 class="font-medium">
    <b class="font-bold poppins">Sean</b> <span class="">Coughlin</span>
  </h1>
  <div class="sm:flex items-center gap-4 hidden">
    {#each links as link, index}
      {#if index !== 0 && index !== links.length - 1}
        <a
          href={link.url}
          class="duration-200 hover:text-violet-400"
          target="_blank"
        >
          {link.name}
        </a>
      {/if}
    {/each}
    <a
      href="Resume.pdf"
      target="_blank"
      class="blueShadow relative overflow-hidden px-5 py-2 group rounded-full bg-white text-slate-950"
    >
      <div
        class="absolute top-0 right-full w-full h-full bg-violet-400 opacity-20 group-hover:translate-x-full z-0 duration-200"
      />
      Resume
    </a>
  </div>
</header>

// components/header.tsx
"use client";

import { links } from "@/lib/data";
import Link from "next/link";
import clsx from "clsx";
import { useActiveSectionContext } from "@/context/active-section-context";

export default function Header() {
  const { activeSection, setActiveSection, setTimeOfLastClick } =
    useActiveSectionContext();

  return (
    <header className="z-999 relative">
      <div className="fixed top-0 left-1/2 h-[3.25rem] w-full rounded-none border border-white border-opacity-40 bg-white bg-opacity-80 shadow-lg shadow-black/[0.03] backdrop-blur-[0.5rem] sm:top-6 sm:h-[3.25rem] sm:w-[23rem] sm:rounded-full dark:bg-gray-950 dark:border-black/40 dark:bg-opacity-75 animate-header-slide-in-down"></div>
      <nav className="flex fixed top-[0.15rem] left-1/2 h-12 -translate-x-1/2 py-2 sm:top-[1.7rem] sm:h-[initial] sm:py-0">
        <ul className="flex w-[22rem] flex-wrap items-center justify-center gap-y-1 text-[0.9rem] font-medium text-gray-700 sm:w-[initial] sm:flex-nowrap sm:gap-5">
          {links.map((link) => (
            <li
              className="h-3/4 flex items-center justify-center relative animate-slide-in-down-delay-1"
              key={link.hash}
            >
              <Link
                className={clsx(
                  "flex w-full items-center justify-center px-3 py-3 hover:text-gray-950 transition dark:text-gray-300 dark:hover:text-gray-50",
                  {
                    "text-gray-950 dark:text-gray-100":
                      activeSection === link.name
                  }
                )}
                href={link.hash}
                onClick={() => {
                  setActiveSection(link.name);
                  setTimeOfLastClick(Date.now());
                }}
              >
                {link.name}

                {link.name === activeSection && (
                  <span className="bg-gray-100 rounded-full absolute inset-0 -z-10 dark:bg-gray-800 transition-all duration-300 ease-out"></span>
                )}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
}
