// components/footer.tsx
export default function Footer() {
  return (
    <footer className="mb-10 px-4 text-center text-gray-500">
      <small className="mb-2 block text-xs">
        &copy; {new Date().getFullYear()} Sean Coughlin
      </small>
      <p className="text-xs mt-2">
        <a
          href="https://github.com/Scc33/Scc33.github.io"
          target="_blank"
          rel="noopener noreferrer"
          className="text-gray-500 hover:text-gray-700 transition-colors underline"
        >
          View source code on GitHub
        </a>
      </p>
    </footer>
  );
}

// src/components/Footer.svelte
<footer
  class="py-20 bg-black border-t border-solid border-violet-950 flex flex-col gap-4 sm:gap-8 justify-center items-center"
>
  <div class="flex flex-col gap-4 items-center justify-center">
    <p><b class="pr-2">Email</b> coughlinscc33@gmail.com</p>
    <p>
      <b class="pr-2">GitHub</b>
      <a
        href="https://github.com/Scc33"
        target="_blank"
        class="text-violet-400 underline">Scc33</a
      >
    </p>
    <p>
      <b class="pr-2">LinkedIn</b>
      <a
        href="https://www.linkedin.com/in/sean-m-coughlin/"
        target="_blank"
        class="text-violet-400 underline">sean-m-coughlin</a
      >
    </p>
    <p>
      <b class="pr-2">Blog</b>
      <a
        href="https://blog.seancoughlin.me"
        target="_blank"
        class="text-violet-400 underline">Hashnode</a
      >
    </p>
    <p>
      <a
        href="assets/Resume.pdf"
        target="_blank"
        class="text-violet-400 underline"
      >
        Resume
      </a>
    </p>
  </div>
</footer>
